/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import javax.swing.JOptionPane;

/**
 *
 * @author Zeynep
 */
public class sudoku_arayuz extends javax.swing.JFrame {
    boolean kontrol;
    int sure;
    kronometre k = new kronometre();
    int [][] Isayilar = new int[9][9];
    /**
     * Creates new form sudoku_arayuz
     */
    public sudoku_arayuz() {
        k.basla();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        yedi_bir = new javax.swing.JTextField();
        yedi_iki = new javax.swing.JTextField();
        yedi_uc = new javax.swing.JTextField();
        sekiz_bir = new javax.swing.JTextField();
        sekiz_iki = new javax.swing.JTextField();
        sekiz_uc = new javax.swing.JTextField();
        dokuz_bir = new javax.swing.JTextField();
        dokuz_iki = new javax.swing.JTextField();
        sekiz_dokuz = new javax.swing.JTextField();
        dokuz_yedi = new javax.swing.JTextField();
        yedi_sekiz = new javax.swing.JTextField();
        dokuz_sekiz = new javax.swing.JTextField();
        yedi_yedi = new javax.swing.JTextField();
        yedi_dort = new javax.swing.JTextField();
        dokuz_alti = new javax.swing.JTextField();
        yedi_alti = new javax.swing.JTextField();
        sekiz_dort = new javax.swing.JTextField();
        dokuz_uc = new javax.swing.JTextField();
        sekiz_bes = new javax.swing.JTextField();
        yedi_bes = new javax.swing.JTextField();
        sekiz_alti = new javax.swing.JTextField();
        dokuz_dort = new javax.swing.JTextField();
        dokuz_bes = new javax.swing.JTextField();
        dokuz_dokuz = new javax.swing.JTextField();
        yedi_dokuz = new javax.swing.JTextField();
        sekiz_yedi = new javax.swing.JTextField();
        sekiz_sekiz = new javax.swing.JTextField();
        alti_yedi = new javax.swing.JTextField();
        alti_bir = new javax.swing.JTextField();
        alti_iki = new javax.swing.JTextField();
        alti_uc = new javax.swing.JTextField();
        bes_bes = new javax.swing.JTextField();
        dort_bes = new javax.swing.JTextField();
        bes_alti = new javax.swing.JTextField();
        alti_dort = new javax.swing.JTextField();
        alti_bes = new javax.swing.JTextField();
        dort_dort = new javax.swing.JTextField();
        alti_alti = new javax.swing.JTextField();
        dort_alti = new javax.swing.JTextField();
        bes_dort = new javax.swing.JTextField();
        dort_yedi = new javax.swing.JTextField();
        alti_dokuz = new javax.swing.JTextField();
        dort_dokuz = new javax.swing.JTextField();
        dort_sekiz = new javax.swing.JTextField();
        dort_bir = new javax.swing.JTextField();
        bes_sekiz = new javax.swing.JTextField();
        dort_iki = new javax.swing.JTextField();
        bes_dokuz = new javax.swing.JTextField();
        dort_uc = new javax.swing.JTextField();
        bes_yedi = new javax.swing.JTextField();
        bes_bir = new javax.swing.JTextField();
        alti_sekiz = new javax.swing.JTextField();
        bes_iki = new javax.swing.JTextField();
        bes_uc = new javax.swing.JTextField();
        uc_alti = new javax.swing.JTextField();
        bir_alti = new javax.swing.JTextField();
        iki_dort = new javax.swing.JTextField();
        uc_yedi = new javax.swing.JTextField();
        iki_yedi = new javax.swing.JTextField();
        uc_sekiz = new javax.swing.JTextField();
        uc_dokuz = new javax.swing.JTextField();
        bir_yedi = new javax.swing.JTextField();
        bir_iki = new javax.swing.JTextField();
        bir_sekiz = new javax.swing.JTextField();
        bir_uc = new javax.swing.JTextField();
        bir_dokuz = new javax.swing.JTextField();
        iki_bir = new javax.swing.JTextField();
        iki_iki = new javax.swing.JTextField();
        iki_sekiz = new javax.swing.JTextField();
        iki_dokuz = new javax.swing.JTextField();
        iki_uc = new javax.swing.JTextField();
        bir_bir = new javax.swing.JTextField();
        uc_bir = new javax.swing.JTextField();
        uc_iki = new javax.swing.JTextField();
        uc_uc = new javax.swing.JTextField();
        iki_bes = new javax.swing.JTextField();
        bir_bes = new javax.swing.JTextField();
        iki_alti = new javax.swing.JTextField();
        uc_dort = new javax.swing.JTextField();
        uc_bes = new javax.swing.JTextField();
        bir_dort = new javax.swing.JTextField();
        buton_kontrol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("SUDOKU");

        yedi_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yedi_iki.setEditable(false);
        yedi_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yedi_iki.setText("6");

        yedi_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_bir.setEditable(false);
        sekiz_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sekiz_bir.setText("4");

        sekiz_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_uc.setEditable(false);
        sekiz_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sekiz_uc.setText("2");
        sekiz_uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sekiz_ucActionPerformed(evt);
            }
        });

        dokuz_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dokuz_iki.setEditable(false);
        dokuz_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dokuz_iki.setText("9");

        sekiz_dokuz.setEditable(false);
        sekiz_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sekiz_dokuz.setText("5");

        dokuz_yedi.setEditable(false);
        dokuz_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dokuz_yedi.setText("4");

        yedi_sekiz.setEditable(false);
        yedi_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yedi_sekiz.setText("9");

        dokuz_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yedi_yedi.setEditable(false);
        yedi_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yedi_yedi.setText("1");

        yedi_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dokuz_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yedi_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dokuz_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        yedi_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_alti.setEditable(false);
        sekiz_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sekiz_alti.setText("9");

        dokuz_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dokuz_bes.setEditable(false);
        dokuz_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dokuz_bes.setText("7");

        dokuz_dokuz.setEditable(false);
        dokuz_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dokuz_dokuz.setText("2");

        yedi_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        sekiz_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        alti_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        alti_bir.setEditable(false);
        alti_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alti_bir.setText("6");

        alti_iki.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        alti_uc.setEditable(false);
        alti_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alti_uc.setText("4");

        bes_bes.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        dort_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bes_alti.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        alti_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        alti_bes.setEditable(false);
        alti_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alti_bes.setText("3");

        dort_dort.setEditable(false);
        dort_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dort_dort.setText("4");

        alti_alti.setEditable(false);
        alti_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alti_alti.setText("2");

        dort_alti.setEditable(false);
        dort_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dort_alti.setText("5");

        bes_dort.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        dort_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        alti_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dort_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dort_sekiz.setEditable(false);
        dort_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dort_sekiz.setText("2");

        dort_bir.setEditable(false);
        dort_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dort_bir.setText("9");

        bes_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dort_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bes_dokuz.setEditable(false);
        bes_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bes_dokuz.setText("4");

        dort_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bes_yedi.setEditable(false);
        bes_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bes_yedi.setText("6");

        bes_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        alti_sekiz.setEditable(false);
        alti_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        alti_sekiz.setText("8");

        bes_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bes_uc.setEditable(false);
        bes_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bes_uc.setText("1");
        bes_uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bes_ucActionPerformed(evt);
            }
        });

        uc_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        iki_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        uc_yedi.setEditable(false);
        uc_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uc_yedi.setText("2");

        iki_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        uc_sekiz.setEditable(false);
        uc_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uc_sekiz.setText("1");

        uc_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_yedi.setEditable(false);
        bir_yedi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bir_yedi.setText("8");

        bir_iki.setEditable(false);
        bir_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bir_iki.setText("4");

        bir_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_dokuz.setEditable(false);
        bir_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bir_dokuz.setText("6");

        iki_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        iki_iki.setEditable(false);
        iki_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iki_iki.setText("1");

        iki_sekiz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        iki_dokuz.setEditable(false);
        iki_dokuz.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iki_dokuz.setText("3");

        iki_uc.setEditable(false);
        iki_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iki_uc.setText("9");
        iki_uc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iki_ucActionPerformed(evt);
            }
        });

        bir_bir.setEditable(false);
        bir_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bir_bir.setText("5");

        uc_bir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        uc_iki.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        uc_uc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        iki_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_bes.setEditable(false);
        bir_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bir_bes.setText("2");

        iki_alti.setEditable(false);
        iki_alti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        iki_alti.setText("7");

        uc_dort.setEditable(false);
        uc_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        uc_dort.setText("3");

        uc_bes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bir_dort.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        buton_kontrol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buton_kontrol.setText("Kontrol Et ");
        buton_kontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_kontrolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alti_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bes_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dort_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dort_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dort_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bes_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bes_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(alti_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alti_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alti_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bes_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dort_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dort_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dort_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bes_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bes_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(alti_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alti_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(alti_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bes_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dort_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dort_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dort_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bes_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bes_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(alti_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(alti_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uc_bir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iki_bir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bir_bir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bir_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bir_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(iki_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iki_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(uc_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uc_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uc_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iki_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bir_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bir_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bir_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(iki_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iki_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(uc_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uc_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(uc_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iki_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bir_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(bir_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bir_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(iki_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(iki_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(uc_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(uc_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buton_kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dokuz_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sekiz_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yedi_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(yedi_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yedi_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(sekiz_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sekiz_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dokuz_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dokuz_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dokuz_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sekiz_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yedi_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(yedi_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yedi_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(sekiz_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sekiz_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(dokuz_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dokuz_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dokuz_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(yedi_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yedi_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sekiz_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sekiz_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(dokuz_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dokuz_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bir_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bir_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bir_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iki_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uc_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bir_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bir_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bir_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iki_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uc_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bir_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bir_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bir_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iki_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iki_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uc_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uc_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dort_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bes_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alti_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dort_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bes_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alti_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dort_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dort_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bes_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bes_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alti_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alti_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yedi_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sekiz_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dokuz_dort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_bes, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_alti, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yedi_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sekiz_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dokuz_bir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_iki, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_uc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yedi_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yedi_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sekiz_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sekiz_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dokuz_yedi, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_sekiz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dokuz_dokuz, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_kontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void iki_ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iki_ucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iki_ucActionPerformed

    private void bes_ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bes_ucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bes_ucActionPerformed

    private void sekiz_ucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sekiz_ucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sekiz_ucActionPerformed
    
    private void buton_kontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_kontrolActionPerformed
        sure = k.bitir();
        degerAl();
        boolean sonuc;
        sonuc = kontrolEt();
        System.out.println(sonuc);
        if(sonuc){//BUrdan devam ettt-----------------------------------------------------------(tek sıkıntı:buraya girmiyor doğru sonuca ulaşamadım yani)
            System.out.println("girdim ha!");
            JOptionPane.showMessageDialog(null,"Doğru Çözüm!Sudokuyu bitirme süren: " + (sure));
        }
        else{
            System.out.println("girdim ha!2");
            JOptionPane.showMessageDialog(null,"Hatalı Çözüm!Ceza dahil bitirme süreniz: " + (sure+20));
        }
    }//GEN-LAST:event_buton_kontrolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sudoku_arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sudoku_arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sudoku_arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sudoku_arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sudoku_arayuz().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alti_alti;
    private javax.swing.JTextField alti_bes;
    private javax.swing.JTextField alti_bir;
    private javax.swing.JTextField alti_dokuz;
    private javax.swing.JTextField alti_dort;
    private javax.swing.JTextField alti_iki;
    private javax.swing.JTextField alti_sekiz;
    private javax.swing.JTextField alti_uc;
    private javax.swing.JTextField alti_yedi;
    private javax.swing.JTextField bes_alti;
    private javax.swing.JTextField bes_bes;
    private javax.swing.JTextField bes_bir;
    private javax.swing.JTextField bes_dokuz;
    private javax.swing.JTextField bes_dort;
    private javax.swing.JTextField bes_iki;
    private javax.swing.JTextField bes_sekiz;
    private javax.swing.JTextField bes_uc;
    private javax.swing.JTextField bes_yedi;
    private javax.swing.JTextField bir_alti;
    private javax.swing.JTextField bir_bes;
    private javax.swing.JTextField bir_bir;
    private javax.swing.JTextField bir_dokuz;
    private javax.swing.JTextField bir_dort;
    private javax.swing.JTextField bir_iki;
    private javax.swing.JTextField bir_sekiz;
    private javax.swing.JTextField bir_uc;
    private javax.swing.JTextField bir_yedi;
    private javax.swing.JButton buton_kontrol;
    private javax.swing.JTextField dokuz_alti;
    private javax.swing.JTextField dokuz_bes;
    private javax.swing.JTextField dokuz_bir;
    private javax.swing.JTextField dokuz_dokuz;
    private javax.swing.JTextField dokuz_dort;
    private javax.swing.JTextField dokuz_iki;
    private javax.swing.JTextField dokuz_sekiz;
    private javax.swing.JTextField dokuz_uc;
    private javax.swing.JTextField dokuz_yedi;
    private javax.swing.JTextField dort_alti;
    private javax.swing.JTextField dort_bes;
    private javax.swing.JTextField dort_bir;
    private javax.swing.JTextField dort_dokuz;
    private javax.swing.JTextField dort_dort;
    private javax.swing.JTextField dort_iki;
    private javax.swing.JTextField dort_sekiz;
    private javax.swing.JTextField dort_uc;
    private javax.swing.JTextField dort_yedi;
    private javax.swing.JTextField iki_alti;
    private javax.swing.JTextField iki_bes;
    private javax.swing.JTextField iki_bir;
    private javax.swing.JTextField iki_dokuz;
    private javax.swing.JTextField iki_dort;
    private javax.swing.JTextField iki_iki;
    private javax.swing.JTextField iki_sekiz;
    private javax.swing.JTextField iki_uc;
    private javax.swing.JTextField iki_yedi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField sekiz_alti;
    private javax.swing.JTextField sekiz_bes;
    private javax.swing.JTextField sekiz_bir;
    private javax.swing.JTextField sekiz_dokuz;
    private javax.swing.JTextField sekiz_dort;
    private javax.swing.JTextField sekiz_iki;
    private javax.swing.JTextField sekiz_sekiz;
    private javax.swing.JTextField sekiz_uc;
    private javax.swing.JTextField sekiz_yedi;
    private javax.swing.JTextField uc_alti;
    private javax.swing.JTextField uc_bes;
    private javax.swing.JTextField uc_bir;
    private javax.swing.JTextField uc_dokuz;
    private javax.swing.JTextField uc_dort;
    private javax.swing.JTextField uc_iki;
    private javax.swing.JTextField uc_sekiz;
    private javax.swing.JTextField uc_uc;
    private javax.swing.JTextField uc_yedi;
    private javax.swing.JTextField yedi_alti;
    private javax.swing.JTextField yedi_bes;
    private javax.swing.JTextField yedi_bir;
    private javax.swing.JTextField yedi_dokuz;
    private javax.swing.JTextField yedi_dort;
    private javax.swing.JTextField yedi_iki;
    private javax.swing.JTextField yedi_sekiz;
    private javax.swing.JTextField yedi_uc;
    private javax.swing.JTextField yedi_yedi;
    // End of variables declaration//GEN-END:variables
    
    public void degerAl(){  
        String[][] Ssayilar;
        Ssayilar = new String[][]{
            {bir_bir.getText(),bir_iki.getText(),bir_uc.getText(),bir_dort.getText(),bir_bes.getText(),bir_alti.getText(),bir_yedi.getText(),bir_sekiz.getText(),bir_dokuz.getText()},
            {iki_bir.getText(),iki_iki.getText(),iki_uc.getText(),iki_dort.getText(),iki_bes.getText(),iki_alti.getText(),iki_yedi.getText(),iki_sekiz.getText(),iki_dokuz.getText()},
            {uc_bir.getText(),uc_iki.getText(),uc_uc.getText(),uc_dort.getText(),uc_bes.getText(),uc_alti.getText(),uc_yedi.getText(),uc_sekiz.getText(),uc_dokuz.getText()},
            {dort_bir.getText(),dort_iki.getText(),dort_uc.getText(),dort_dort.getText(),dort_bes.getText(),dort_alti.getText(),dort_yedi.getText(),dort_sekiz.getText(),dort_dokuz.getText()},
            {bes_bir.getText(),bes_iki.getText(),bes_uc.getText(),bes_dort.getText(),bes_bes.getText(),bes_alti.getText(),bes_yedi.getText(),bes_sekiz.getText(),bes_dokuz.getText()},
            {alti_bir.getText(),alti_iki.getText(),alti_uc.getText(),alti_dort.getText(),alti_bes.getText(),alti_alti.getText(),alti_yedi.getText(),alti_sekiz.getText(),alti_dokuz.getText()},
            {yedi_bir.getText(),yedi_iki.getText(),yedi_uc.getText(),yedi_dort.getText(),yedi_bes.getText(),yedi_alti.getText(),yedi_yedi.getText(),yedi_sekiz.getText(),yedi_dokuz.getText()},
            {sekiz_bir.getText(),sekiz_iki.getText(),sekiz_uc.getText(),sekiz_dort.getText(),sekiz_bes.getText(),sekiz_alti.getText(),sekiz_yedi.getText(),sekiz_sekiz.getText(),sekiz_dokuz.getText()},
            {dokuz_bir.getText(),dokuz_iki.getText(),dokuz_uc.getText(),dokuz_dort.getText(),dokuz_bes.getText(),dokuz_alti.getText(),dokuz_yedi.getText(),dokuz_sekiz.getText(),dokuz_dokuz.getText()}
        }; 
        for(int i = 0; i < 9 ; i++){
            for(int j = 0; j < 9 ; j++){
                Isayilar[i][j] = Integer.parseInt(Ssayilar[i][j]);
            }
        }
    }
    public boolean kontrolEt(){ 
        int a;
        for(int i = 0; i < 9 ; i++){
            a = 1;
            for(int j = 0; j < 9 ; j++){
                for(int x=a ;x<9;x++){
                    if(Isayilar[i][j] == Isayilar[i][x]){
                        return false;
                    }
                }
                a++;
            }
        }return true;
    }
}
